### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by pel-daniel** [minimalistOrg/minimalistIdeV2#3]
### Closing a bubble

https://user-images.githubusercontent.com/980388/166739885-1e12c5eb-a747-4a17-a037-be7a44ef051b.mov

https://user-images.githubusercontent.com/980388/166739968-bf04ee84-e119-43ce-9385-976d52ad80ba.mov

**Comment by Usielrivas** [comment]
Bug Fixed
#[0ca6783](https://github.com/minimalistOrg/minimalistIdeV2/commit/0ca67833321eff05699843d29b1967392260360b)
