### ISSUE TITLE
Closing and reopening a bubble with nested elements opened should only open one bubble

### ISSUE THREAD

**Issue by pel-daniel** [minimalistOrg/minimalistIdeV2#5]
https://user-images.githubusercontent.com/980388/171464376-9e8eabf7-5ebd-4181-a726-9a990436bf7b.mp4

The `division` bubble has a `show` bubble opened in the same BubbleRow
If I close the `division` bubble and then open it again, only open the `division` bubble.

**Comment by Usielrivas** [comment]
Bug fixed: [5354565](https://github.com/minimalistOrg/minimalistIdeV2/commit/5354565bc3d3d73be513db39bbcadb023d04ac82)
