### ISSUE TITLE
Hover shouldn't highlight bubble in different RowBubble

### ISSUE THREAD

**Issue by pel-daniel** [minimalistOrg/minimalistIdeV2#8]
https://user-images.githubusercontent.com/980388/170366944-08708d8d-b39e-4cf7-a1f5-b82a53a1c3c7.mp4

**Comment by Usielrivas** [comment]
bug fixed: [a6a4adb](https://github.com/minimalistOrg/minimalistIdeV2/commit/a6a4adbdc2e9d246967d32de44a49bb659dc97af)
